/**
 * CreatorBoost AI - Comprehensive Keyword Research Database
 * 500+ keywords with search volume, difficulty, intent, and target URLs
 * Last Updated: June 2026
 */

export interface Keyword {
  keyword: string;
  searchVolume: number;
  difficulty: number; // 1-100
  intent: 'informational' | 'transactional' | 'navigational';
  relatedKeywords: string[];
  contentType: 'blog' | 'tool' | 'landing' | 'guide' | 'comparison';
  targetUrl: string;
  category: string;
}

// ===== PRIMARY KEYWORDS (High Volume) =====
export const PRIMARY_KEYWORDS: Keyword[] = [
  {
    keyword: 'image compressor online',
    searchVolume: 100000,
    difficulty: 45,
    intent: 'transactional',
    relatedKeywords: ['compress image', 'image compressor', 'reduce image size', 'online image compressor'],
    contentType: 'tool',
    targetUrl: '/tools/image-compressor',
    category: 'image',
  },
  {
    keyword: 'pdf merger',
    searchVolume: 50000,
    difficulty: 40,
    intent: 'transactional',
    relatedKeywords: ['merge pdf', 'combine pdf', 'pdf joiner', 'merge pdf files'],
    contentType: 'tool',
    targetUrl: '/tools/pdf-merger',
    category: 'pdf',
  },
  {
    keyword: 'youtube title generator',
    searchVolume: 30000,
    difficulty: 35,
    intent: 'transactional',
    relatedKeywords: ['youtube title maker', 'video title generator', 'youtube title ideas'],
    contentType: 'tool',
    targetUrl: '/tools/youtube-title-generator',
    category: 'youtube',
  },
  {
    keyword: 'background remover',
    searchVolume: 80000,
    difficulty: 50,
    intent: 'transactional',
    relatedKeywords: ['remove background', 'bg remover', 'remove image background', 'transparent background'],
    contentType: 'tool',
    targetUrl: '/tools/ai-bg-remover',
    category: 'image',
  },
  {
    keyword: 'qr code generator',
    searchVolume: 200000,
    difficulty: 55,
    intent: 'transactional',
    relatedKeywords: ['create qr code', 'qr code maker', 'free qr code generator', 'qr code online'],
    contentType: 'tool',
    targetUrl: '/tools/qr-code-generator',
    category: 'utility',
  },
  {
    keyword: 'pdf compressor',
    searchVolume: 45000,
    difficulty: 42,
    intent: 'transactional',
    relatedKeywords: ['compress pdf', 'reduce pdf size', 'shrink pdf', 'pdf optimizer'],
    contentType: 'tool',
    targetUrl: '/tools/pdf-compressor',
    category: 'pdf',
  },
  {
    keyword: 'youtube thumbnail downloader',
    searchVolume: 35000,
    difficulty: 30,
    intent: 'transactional',
    relatedKeywords: ['download youtube thumbnail', 'youtube thumbnail grabber', 'save youtube thumbnail'],
    contentType: 'tool',
    targetUrl: '/tools/youtube-thumbnail-downloader',
    category: 'youtube',
  },
  {
    keyword: 'password generator',
    searchVolume: 60000,
    difficulty: 38,
    intent: 'transactional',
    relatedKeywords: ['generate password', 'strong password generator', 'random password', 'secure password'],
    contentType: 'tool',
    targetUrl: '/tools/password-generator',
    category: 'utility',
  },
  {
    keyword: 'word counter',
    searchVolume: 40000,
    difficulty: 30,
    intent: 'transactional',
    relatedKeywords: ['word count', 'count words', 'word counter online', 'character counter'],
    contentType: 'tool',
    targetUrl: '/tools/word-counter',
    category: 'utility',
  },
  {
    keyword: 'color picker',
    searchVolume: 70000,
    difficulty: 45,
    intent: 'transactional',
    relatedKeywords: ['color code converter', 'hex color picker', 'rgb color picker', 'color palette generator'],
    contentType: 'tool',
    targetUrl: '/tools/color-converter',
    category: 'utility',
  },
  {
    keyword: 'base64 encoder',
    searchVolume: 25000,
    difficulty: 32,
    intent: 'transactional',
    relatedKeywords: ['base64 decode', 'base64 converter', 'encode to base64', 'base64 online'],
    contentType: 'tool',
    targetUrl: '/tools/base64-encoder',
    category: 'developer',
  },
  {
    keyword: 'json formatter',
    searchVolume: 30000,
    difficulty: 28,
    intent: 'transactional',
    relatedKeywords: ['json validator', 'json beautifier', 'format json', 'json minify'],
    contentType: 'tool',
    targetUrl: '/tools/json-formatter',
    category: 'developer',
  },
  {
    keyword: 'unit converter',
    searchVolume: 55000,
    difficulty: 50,
    intent: 'transactional',
    relatedKeywords: ['unit converter online', 'measurement converter', 'convert units', 'unit conversion calculator'],
    contentType: 'tool',
    targetUrl: '/tools/unit-converter',
    category: 'utility',
  },
  {
    keyword: 'bmi calculator',
    searchVolume: 80000,
    difficulty: 48,
    intent: 'transactional',
    relatedKeywords: ['bmi calculator online', 'body mass index', 'calculate bmi', 'bmi chart'],
    contentType: 'tool',
    targetUrl: '/tools/bmi-calculator',
    category: 'finance',
  },
  {
    keyword: 'emi calculator',
    searchVolume: 45000,
    difficulty: 40,
    intent: 'transactional',
    relatedKeywords: ['loan emi calculator', 'home loan emi', 'calculate emi', 'emi calculator online'],
    contentType: 'tool',
    targetUrl: '/tools/loan-emi-calculator',
    category: 'finance',
  },
];

// ===== LONG-TAIL KEYWORDS (Low Competition) =====
export const LONG_TAIL_KEYWORDS: Keyword[] = [
  {
    keyword: 'how to compress image without losing quality free',
    searchVolume: 8000,
    difficulty: 15,
    intent: 'informational',
    relatedKeywords: ['compress image free', 'image compression without quality loss', 'best image compressor free'],
    contentType: 'blog',
    targetUrl: '/blog/how-to-compress-images-without-losing-quality',
    category: 'image',
  },
  {
    keyword: 'merge pdf files online free no sign up',
    searchVolume: 12000,
    difficulty: 20,
    intent: 'transactional',
    relatedKeywords: ['merge pdf online', 'free pdf merger', 'combine pdf free', 'pdf joiner online'],
    contentType: 'tool',
    targetUrl: '/tools/pdf-merger',
    category: 'pdf',
  },
  {
    keyword: 'youtube title generator ai free',
    searchVolume: 5000,
    difficulty: 12,
    intent: 'transactional',
    relatedKeywords: ['ai youtube titles', 'free youtube title maker', 'generate youtube titles'],
    contentType: 'tool',
    targetUrl: '/tools/youtube-title-generator',
    category: 'youtube',
  },
  {
    keyword: 'remove background from image online free',
    searchVolume: 15000,
    difficulty: 25,
    intent: 'transactional',
    relatedKeywords: ['free bg remover', 'remove bg online', 'transparent background maker'],
    contentType: 'tool',
    targetUrl: '/tools/ai-bg-remover',
    category: 'image',
  },
  {
    keyword: 'convert pdf to jpg high quality',
    searchVolume: 10000,
    difficulty: 22,
    intent: 'transactional',
    relatedKeywords: ['pdf to image', 'pdf to png', 'convert pdf to image', 'pdf to jpg converter'],
    contentType: 'tool',
    targetUrl: '/tools/pdf-to-jpg',
    category: 'pdf',
  },
  {
    keyword: 'how to get 1000 youtube subscribers fast',
    searchVolume: 6000,
    difficulty: 18,
    intent: 'informational',
    relatedKeywords: ['youtube subscriber growth', 'get youtube subscribers', 'grow youtube channel'],
    contentType: 'blog',
    targetUrl: '/blog/how-to-get-first-1000-youtube-subscribers',
    category: 'youtube',
  },
  {
    keyword: 'best time to post on youtube 2026',
    searchVolume: 4000,
    difficulty: 10,
    intent: 'informational',
    relatedKeywords: ['youtube upload time', 'when to post youtube', 'youtube posting schedule'],
    contentType: 'blog',
    targetUrl: '/blog/best-time-to-upload-youtube-videos',
    category: 'youtube',
  },
  {
    keyword: 'seo checklist for beginners 2026',
    searchVolume: 3000,
    difficulty: 8,
    intent: 'informational',
    relatedKeywords: ['seo guide', 'seo tips', 'seo optimization', 'search engine optimization'],
    contentType: 'blog',
    targetUrl: '/blog/complete-seo-checklist-2026',
    category: 'seo',
  },
  {
    keyword: 'how to write blog posts that rank on google',
    searchVolume: 5000,
    difficulty: 12,
    intent: 'informational',
    relatedKeywords: ['blog seo', 'write seo blog', 'blog post optimization', 'rank blog on google'],
    contentType: 'blog',
    targetUrl: '/blog/write-blog-posts-that-rank',
    category: 'content',
  },
  {
    keyword: 'free qr code generator with logo',
    searchVolume: 8000,
    difficulty: 18,
    intent: 'transactional',
    relatedKeywords: ['custom qr code', 'qr code with image', 'branded qr code', 'qr code with logo'],
    contentType: 'tool',
    targetUrl: '/tools/qr-code-generator',
    category: 'utility',
  },
  {
    keyword: 'youtube seo complete guide',
    searchVolume: 4000,
    difficulty: 15,
    intent: 'informational',
    relatedKeywords: ['youtube seo tips', 'youtube optimization', 'rank youtube videos', 'youtube search ranking'],
    contentType: 'blog',
    targetUrl: '/blog/youtube-seo-complete-guide-ranking-1',
    category: 'youtube',
  },
  {
    keyword: 'how to create youtube thumbnails that get clicks',
    searchVolume: 3500,
    difficulty: 10,
    intent: 'informational',
    relatedKeywords: ['youtube thumbnail design', 'thumbnail tips', 'high ctr thumbnails', 'thumbnail templates'],
    contentType: 'blog',
    targetUrl: '/blog/youtube-thumbnail-designs-high-ctr',
    category: 'youtube',
  },
  {
    keyword: 'email subject line generator',
    searchVolume: 7000,
    difficulty: 20,
    intent: 'transactional',
    relatedKeywords: ['email subject lines', 'email title generator', 'catchy subject lines', 'email open rate'],
    contentType: 'tool',
    targetUrl: '/tools/email-subject-generator',
    category: 'content',
  },
  {
    keyword: 'content calendar template free',
    searchVolume: 9000,
    difficulty: 22,
    intent: 'transactional',
    relatedKeywords: ['editorial calendar', 'content planning', 'social media calendar', 'blog calendar'],
    contentType: 'tool',
    targetUrl: '/tools/content-calendar',
    category: 'content',
  },
  {
    keyword: 'how to make money on youtube without 1000 subscribers',
    searchVolume: 6000,
    difficulty: 15,
    intent: 'informational',
    relatedKeywords: ['youtube monetization', 'youtube income', 'earn from youtube', 'youtube affiliate marketing'],
    contentType: 'blog',
    targetUrl: '/blog/make-money-youtube-without-1000-subscribers',
    category: 'youtube',
  },
  {
    keyword: 'regex tester online',
    searchVolume: 5000,
    difficulty: 15,
    intent: 'transactional',
    relatedKeywords: ['regex test', 'regular expression tester', 'regex validator', 'regex checker'],
    contentType: 'tool',
    targetUrl: '/tools/regex-tester',
    category: 'developer',
  },
  {
    keyword: 'css minifier online',
    searchVolume: 4000,
    difficulty: 12,
    intent: 'transactional',
    relatedKeywords: ['minify css', 'css compressor', 'css minify', 'reduce css size'],
    contentType: 'tool',
    targetUrl: '/tools/css-minifier',
    category: 'developer',
  },
  {
    keyword: 'url encoder decoder',
    searchVolume: 6000,
    difficulty: 18,
    intent: 'transactional',
    relatedKeywords: ['url encode', 'url decode', 'percent encoding', 'url encoding online'],
    contentType: 'tool',
    targetUrl: '/tools/url-encoder',
    category: 'developer',
  },
  {
    keyword: 'hash generator online',
    searchVolume: 4500,
    difficulty: 14,
    intent: 'transactional',
    relatedKeywords: ['md5 generator', 'sha256 generator', 'hash generator', 'checksum calculator'],
    contentType: 'tool',
    targetUrl: '/tools/hash-generator',
    category: 'developer',
  },
  {
    keyword: 'markdown to html converter',
    searchVolume: 3500,
    difficulty: 10,
    intent: 'transactional',
    relatedKeywords: ['markdown converter', 'md to html', 'markdown parser', 'markdown online'],
    contentType: 'tool',
    targetUrl: '/tools/markdown-to-html',
    category: 'developer',
  },
  {
    keyword: 'html to markdown converter',
    searchVolume: 3000,
    difficulty: 10,
    intent: 'transactional',
    relatedKeywords: ['html to md', 'convert html to markdown', 'html markdown converter'],
    contentType: 'tool',
    targetUrl: '/tools/html-to-markdown',
    category: 'developer',
  },
  {
    keyword: 'youtube algorithm 2026 explained',
    searchVolume: 5000,
    difficulty: 12,
    intent: 'informational',
    relatedKeywords: ['youtube algorithm', 'youtube ranking', 'how youtube algorithm works', 'youtube recommendation'],
    contentType: 'blog',
    targetUrl: '/blog/youtube-algorithm-2026',
    category: 'youtube',
  },
  {
    keyword: 'ai tools for content creators',
    searchVolume: 6000,
    difficulty: 15,
    intent: 'informational',
    relatedKeywords: ['ai content tools', 'ai for creators', 'best ai tools', 'ai writing tools'],
    contentType: 'blog',
    targetUrl: '/blog/best-ai-tools-content-creators',
    category: 'ai',
  },
  {
    keyword: 'image format converter online',
    searchVolume: 12000,
    difficulty: 25,
    intent: 'transactional',
    relatedKeywords: ['convert image format', 'png to jpg', 'jpg to webp', 'image converter free'],
    contentType: 'tool',
    targetUrl: '/tools/image-converter',
    category: 'image',
  },
  {
    keyword: 'pdf to word converter free',
    searchVolume: 30000,
    difficulty: 40,
    intent: 'transactional',
    relatedKeywords: ['pdf to docx', 'convert pdf to word', 'pdf to text', 'edit pdf'],
    contentType: 'tool',
    targetUrl: '/tools/pdf-to-word',
    category: 'pdf',
  },
  {
    keyword: 'social media post generator',
    searchVolume: 5000,
    difficulty: 15,
    intent: 'transactional',
    relatedKeywords: ['social media content', 'post generator', 'caption generator', 'social media tool'],
    contentType: 'tool',
    targetUrl: '/tools/social-post-generator',
    category: 'content',
  },
  {
    keyword: 'blog title generator',
    searchVolume: 8000,
    difficulty: 18,
    intent: 'transactional',
    relatedKeywords: ['blog headline generator', 'title generator', 'headline ideas', 'blog title ideas'],
    contentType: 'tool',
    targetUrl: '/tools/blog-title-generator',
    category: 'content',
  },
  {
    keyword: 'percentage calculator online',
    searchVolume: 25000,
    difficulty: 30,
    intent: 'transactional',
    relatedKeywords: ['percentage calculator', 'calculate percentage', 'percent calculator', 'percentage formula'],
    contentType: 'tool',
    targetUrl: '/tools/percentage-calculator',
    category: 'finance',
  },
  {
    keyword: 'age calculator exact',
    searchVolume: 20000,
    difficulty: 25,
    intent: 'transactional',
    relatedKeywords: ['age calculator', 'calculate age', 'age from birthday', 'how old am i'],
    contentType: 'tool',
    targetUrl: '/tools/age-calculator',
    category: 'finance',
  },
  {
    keyword: 'date difference calculator',
    searchVolume: 15000,
    difficulty: 20,
    intent: 'transactional',
    relatedKeywords: ['days between dates', 'date calculator', 'time between dates', 'date diff'],
    contentType: 'tool',
    targetUrl: '/tools/date-difference',
    category: 'finance',
  },
  {
    keyword: 'sip calculator online',
    searchVolume: 18000,
    difficulty: 28,
    intent: 'transactional',
    relatedKeywords: ['sip return calculator', 'mutual fund calculator', 'investment calculator', 'sip investment'],
    contentType: 'tool',
    targetUrl: '/tools/sip-calculator',
    category: 'finance',
  },
  {
    keyword: 'loan comparison calculator',
    searchVolume: 8000,
    difficulty: 18,
    intent: 'transactional',
    relatedKeywords: ['compare loans', 'loan calculator', 'best loan rate', 'emi comparison'],
    contentType: 'tool',
    targetUrl: '/tools/loan-comparison',
    category: 'finance',
  },
  {
    keyword: 'content marketing strategy for beginners',
    searchVolume: 4000,
    difficulty: 12,
    intent: 'informational',
    relatedKeywords: ['content marketing', 'marketing strategy', 'content plan', 'digital marketing strategy'],
    contentType: 'blog',
    targetUrl: '/blog/content-marketing-strategy-beginners',
    category: 'content',
  },
  {
    keyword: 'on page seo tips',
    searchVolume: 6000,
    difficulty: 18,
    intent: 'informational',
    relatedKeywords: ['on page seo', 'seo optimization', 'website seo', 'seo tips'],
    contentType: 'blog',
    targetUrl: '/blog/on-page-seo-optimization-tips',
    category: 'seo',
  },
  {
    keyword: 'keyword research for free',
    searchVolume: 5000,
    difficulty: 15,
    intent: 'informational',
    relatedKeywords: ['free keyword research', 'keyword research tools', 'seo keywords', 'find keywords'],
    contentType: 'blog',
    targetUrl: '/blog/keyword-research-for-free',
    category: 'seo',
  },
  {
    keyword: 'how to build backlinks',
    searchVolume: 7000,
    difficulty: 20,
    intent: 'informational',
    relatedKeywords: ['link building', 'backlink strategy', 'get backlinks', 'seo backlinks'],
    contentType: 'blog',
    targetUrl: '/blog/build-backlinks-2026',
    category: 'seo',
  },
  {
    keyword: 'youtube video ideas for beginners',
    searchVolume: 8000,
    difficulty: 15,
    intent: 'informational',
    relatedKeywords: ['youtube ideas', 'video ideas', 'youtube content ideas', 'what to make on youtube'],
    contentType: 'blog',
    targetUrl: '/blog/50-youtube-video-ideas-beginners',
    category: 'youtube',
  },
  {
    keyword: 'email marketing best practices',
    searchVolume: 5000,
    difficulty: 18,
    intent: 'informational',
    relatedKeywords: ['email marketing tips', 'email campaign', 'email strategy', 'newsletter best practices'],
    contentType: 'blog',
    targetUrl: '/blog/email-marketing-best-practices',
    category: 'marketing',
  },
  {
    keyword: 'meta description generator',
    searchVolume: 4000,
    difficulty: 12,
    intent: 'transactional',
    relatedKeywords: ['meta description', 'seo description', 'meta tag generator', 'description writer'],
    contentType: 'tool',
    targetUrl: '/tools/meta-description-generator',
    category: 'seo',
  },
  {
    keyword: 'ai image upscaler free',
    searchVolume: 6000,
    difficulty: 15,
    intent: 'transactional',
    relatedKeywords: ['upscale image', 'image enhancer', 'increase image resolution', 'ai upscaler'],
    contentType: 'tool',
    targetUrl: '/tools/ai-image-upscaler',
    category: 'image',
  },
  {
    keyword: 'grammar checker online',
    searchVolume: 15000,
    difficulty: 30,
    intent: 'transactional',
    relatedKeywords: ['check grammar', 'spelling checker', 'grammar tool', 'proofread text'],
    contentType: 'tool',
    targetUrl: '/tools/grammar-checker',
    category: 'content',
  },
  {
    keyword: 'content paraphraser',
    searchVolume: 5000,
    difficulty: 15,
    intent: 'transactional',
    relatedKeywords: ['paraphrase tool', 'rewrite text', 'text rephraser', 'paraphrase online'],
    contentType: 'tool',
    targetUrl: '/tools/content-paraphraser',
    category: 'content',
  },
  {
    keyword: 'youtube shorts vs long videos',
    searchVolume: 3000,
    difficulty: 8,
    intent: 'informational',
    relatedKeywords: ['youtube shorts', 'shorts vs long form', 'youtube short videos', 'youtube strategy'],
    contentType: 'blog',
    targetUrl: '/blog/youtube-shorts-vs-long-videos',
    category: 'youtube',
  },
  {
    keyword: 'digital marketing strategy small business',
    searchVolume: 4000,
    difficulty: 15,
    intent: 'informational',
    relatedKeywords: ['small business marketing', 'digital marketing tips', 'marketing plan', 'online marketing'],
    contentType: 'blog',
    targetUrl: '/blog/digital-marketing-strategy-small-business',
    category: 'marketing',
  },
  {
    keyword: 'ai text to image generator',
    searchVolume: 10000,
    difficulty: 25,
    intent: 'transactional',
    relatedKeywords: ['ai image generator', 'text to image ai', 'generate image from text', 'ai art generator'],
    contentType: 'tool',
    targetUrl: '/tools/ai-text-to-image',
    category: 'ai',
  },
  {
    keyword: 'ai code generator',
    searchVolume: 6000,
    difficulty: 18,
    intent: 'transactional',
    relatedKeywords: ['code generator ai', 'ai programming', 'generate code', 'ai code writer'],
    contentType: 'tool',
    targetUrl: '/tools/ai-code-generator',
    category: 'ai',
  },
  {
    keyword: 'ai translator online',
    searchVolume: 8000,
    difficulty: 22,
    intent: 'transactional',
    relatedKeywords: ['translate text', 'ai translation', 'online translator', 'free translation'],
    contentType: 'tool',
    targetUrl: '/tools/ai-translator',
    category: 'ai',
  },
  {
    keyword: 'sentiment analysis tool',
    searchVolume: 4000,
    difficulty: 15,
    intent: 'transactional',
    relatedKeywords: ['sentiment analyzer', 'text sentiment', 'emotion detection', 'opinion mining'],
    contentType: 'tool',
    targetUrl: '/tools/ai-sentiment-analyzer',
    category: 'ai',
  },
  {
    keyword: 'ai document summarizer',
    searchVolume: 5000,
    difficulty: 15,
    intent: 'transactional',
    relatedKeywords: ['summarize document', 'text summarizer', 'pdf summarizer', 'ai summary'],
    contentType: 'tool',
    targetUrl: '/tools/ai-document-summarizer',
    category: 'ai',
  },
  {
    keyword: 'youtube tag generator',
    searchVolume: 7000,
    difficulty: 18,
    intent: 'transactional',
    relatedKeywords: ['youtube tags', 'video tags', 'youtube seo tags', 'tag generator'],
    contentType: 'tool',
    targetUrl: '/tools/youtube-tag-generator',
    category: 'youtube',
  },
  {
    keyword: 'youtube description generator',
    searchVolume: 5000,
    difficulty: 14,
    intent: 'transactional',
    relatedKeywords: ['youtube description', 'video description', 'seo description youtube'],
    contentType: 'tool',
    targetUrl: '/tools/youtube-description-generator',
    category: 'youtube',
  },
  {
    keyword: 'youtube hashtag generator',
    searchVolume: 4000,
    difficulty: 12,
    intent: 'transactional',
    relatedKeywords: ['youtube hashtags', 'video hashtags', 'trending hashtags youtube'],
    contentType: 'tool',
    targetUrl: '/tools/youtube-hashtag-generator',
    category: 'youtube',
  },
  {
    keyword: 'youtube channel analyzer',
    searchVolume: 3000,
    difficulty: 10,
    intent: 'transactional',
    relatedKeywords: ['youtube analytics', 'channel stats', 'youtube channel growth', 'channel analysis'],
    contentType: 'tool',
    targetUrl: '/tools/youtube-channel-analyzer',
    category: 'youtube',
  },
  {
    keyword: 'youtube script writer',
    searchVolume: 4000,
    difficulty: 12,
    intent: 'transactional',
    relatedKeywords: ['video script', 'youtube script template', 'script generator', 'video outline'],
    contentType: 'tool',
    targetUrl: '/tools/youtube-script-writer',
    category: 'youtube',
  },
  {
    keyword: 'youtube seo checker',
    searchVolume: 3000,
    difficulty: 10,
    intent: 'transactional',
    relatedKeywords: ['youtube seo score', 'video seo analyzer', 'youtube optimization tool'],
    contentType: 'tool',
    targetUrl: '/tools/youtube-seo-checker',
    category: 'youtube',
  },
  {
    keyword: 'youtube comment reply generator',
    searchVolume: 2000,
    difficulty: 8,
    intent: 'transactional',
    relatedKeywords: ['youtube reply', 'comment reply tool', 'auto reply youtube'],
    contentType: 'tool',
    targetUrl: '/tools/youtube-comment-replies',
    category: 'youtube',
  },
  {
    keyword: 'youtube video ideas generator',
    searchVolume: 6000,
    difficulty: 14,
    intent: 'transactional',
    relatedKeywords: ['video ideas', 'youtube content ideas', 'what to make on youtube'],
    contentType: 'tool',
    targetUrl: '/tools/youtube-video-ideas',
    category: 'youtube',
  },
  {
    keyword: 'image to base64 converter',
    searchVolume: 4000,
    difficulty: 12,
    intent: 'transactional',
    relatedKeywords: ['image base64', 'convert image to base64', 'base64 image'],
    contentType: 'tool',
    targetUrl: '/tools/image-to-base64',
    category: 'image',
  },
  {
    keyword: 'base64 to image converter',
    searchVolume: 3500,
    difficulty: 10,
    intent: 'transactional',
    relatedKeywords: ['decode base64 image', 'base64 image decoder', 'convert base64 to png'],
    contentType: 'tool',
    targetUrl: '/tools/base64-to-image',
    category: 'image',
  },
  {
    keyword: 'image metadata viewer',
    searchVolume: 3000,
    difficulty: 10,
    intent: 'transactional',
    relatedKeywords: ['exif viewer', 'image properties', 'photo metadata', 'exif data viewer'],
    contentType: 'tool',
    targetUrl: '/tools/image-metadata',
    category: 'image',
  },
  {
    keyword: 'color picker from image',
    searchVolume: 5000,
    difficulty: 14,
    intent: 'transactional',
    relatedKeywords: ['pick color from image', 'eyedropper tool', 'image color picker', 'extract colors'],
    contentType: 'tool',
    targetUrl: '/tools/color-picker',
    category: 'image',
  },
  {
    keyword: 'image splitter online',
    searchVolume: 3000,
    difficulty: 10,
    intent: 'transactional',
    relatedKeywords: ['split image', 'cut image into grid', 'image grid splitter', 'divide image'],
    contentType: 'tool',
    targetUrl: '/tools/image-splitter',
    category: 'image',
  },
  {
    keyword: 'image merger collage maker',
    searchVolume: 4000,
    difficulty: 12,
    intent: 'transactional',
    relatedKeywords: ['combine images', 'photo collage', 'merge photos', 'image collage'],
    contentType: 'tool',
    targetUrl: '/tools/image-merger',
    category: 'image',
  },
  {
    keyword: 'favicon generator',
    searchVolume: 8000,
    difficulty: 18,
    intent: 'transactional',
    relatedKeywords: ['create favicon', 'favicon maker', 'ico generator', 'website icon'],
    contentType: 'tool',
    targetUrl: '/tools/favicon-generator',
    category: 'image',
  },
  {
    keyword: 'pdf page numberer',
    searchVolume: 2500,
    difficulty: 8,
    intent: 'transactional',
    relatedKeywords: ['add page numbers to pdf', 'number pdf pages', 'pdf page numbers'],
    contentType: 'tool',
    targetUrl: '/tools/pdf-page-numberer',
    category: 'pdf',
  },
  {
    keyword: 'pdf watermark adder',
    searchVolume: 2000,
    difficulty: 8,
    intent: 'transactional',
    relatedKeywords: ['add watermark to pdf', 'pdf watermark', 'stamp pdf'],
    contentType: 'tool',
    targetUrl: '/tools/pdf-watermark',
    category: 'pdf',
  },
  {
    keyword: 'pdf password protector',
    searchVolume: 3000,
    difficulty: 10,
    intent: 'transactional',
    relatedKeywords: ['protect pdf', 'encrypt pdf', 'lock pdf', 'pdf password'],
    contentType: 'tool',
    targetUrl: '/tools/pdf-password-protector',
    category: 'pdf',
  },
  {
    keyword: 'pdf metadata editor',
    searchVolume: 1500,
    difficulty: 6,
    intent: 'transactional',
    relatedKeywords: ['edit pdf metadata', 'pdf properties', 'change pdf info'],
    contentType: 'tool',
    targetUrl: '/tools/pdf-metadata-editor',
    category: 'pdf',
  },
  {
    keyword: 'pdf unlocker free',
    searchVolume: 4000,
    difficulty: 12,
    intent: 'transactional',
    relatedKeywords: ['unlock pdf', 'remove pdf password', 'pdf unlock', 'decrypt pdf'],
    contentType: 'tool',
    targetUrl: '/tools/pdf-unlocker',
    category: 'pdf',
  },
  {
    keyword: 'hashtag generator for youtube',
    searchVolume: 3500,
    difficulty: 10,
    intent: 'transactional',
    relatedKeywords: ['youtube hashtags', 'video hashtags', 'trending hashtags'],
    contentType: 'tool',
    targetUrl: '/tools/youtube-hashtag-generator',
    category: 'youtube',
  },
  {
    keyword: 'image filter online',
    searchVolume: 5000,
    difficulty: 15,
    intent: 'transactional',
    relatedKeywords: ['photo filters', 'image effects', 'apply filter to image', 'online photo editor'],
    contentType: 'tool',
    targetUrl: '/tools/image-filters',
    category: 'image',
  },
  {
    keyword: 'ai chatbot online',
    searchVolume: 8000,
    difficulty: 22,
    intent: 'transactional',
    relatedKeywords: ['ai chat', 'chatbot', 'ai assistant', 'talk to ai'],
    contentType: 'tool',
    targetUrl: '/tools/ai-chatbot',
    category: 'ai',
  },
  {
    keyword: 'image compressor for email',
    searchVolume: 3000,
    difficulty: 10,
    intent: 'transactional',
    relatedKeywords: ['compress image for email', 'reduce image size email', 'shrink image attachment'],
    contentType: 'blog',
    targetUrl: '/blog/how-to-compress-images-without-losing-quality',
    category: 'image',
  },
  {
    keyword: 'merge pdf for free',
    searchVolume: 12000,
    difficulty: 22,
    intent: 'transactional',
    relatedKeywords: ['free pdf merge', 'combine pdf free', 'pdf joiner free'],
    contentType: 'tool',
    targetUrl: '/tools/pdf-merger',
    category: 'pdf',
  },
  {
    keyword: 'compress pdf online free',
    searchVolume: 10000,
    difficulty: 20,
    intent: 'transactional',
    relatedKeywords: ['free pdf compressor', 'reduce pdf size free', 'shrink pdf online'],
    contentType: 'tool',
    targetUrl: '/tools/pdf-compressor',
    category: 'pdf',
  },
  {
    keyword: 'how to create a youtube channel',
    searchVolume: 15000,
    difficulty: 25,
    intent: 'informational',
    relatedKeywords: ['start youtube channel', 'youtube channel setup', 'begin youtube channel'],
    contentType: 'blog',
    targetUrl: '/blog/how-to-get-first-1000-youtube-subscribers',
    category: 'youtube',
  },
  {
    keyword: 'best ai tools for writers',
    searchVolume: 5000,
    difficulty: 15,
    intent: 'informational',
    relatedKeywords: ['ai writing tools', 'ai for writers', 'best ai content tools'],
    contentType: 'blog',
    targetUrl: '/blog/best-ai-tools-content-creators',
    category: 'ai',
  },
  {
    keyword: 'how to write viral youtube titles',
    searchVolume: 4000,
    difficulty: 12,
    intent: 'informational',
    relatedKeywords: ['viral titles', 'youtube title tips', 'click-worthy titles'],
    contentType: 'blog',
    targetUrl: '/blog/write-viral-youtube-titles',
    category: 'youtube',
  },
  {
    keyword: 'conversion rate optimization tips',
    searchVolume: 3500,
    difficulty: 15,
    intent: 'informational',
    relatedKeywords: ['cro tips', 'increase conversions', 'conversion optimization', 'landing page optimization'],
    contentType: 'blog',
    targetUrl: '/blog/conversion-rate-optimization',
    category: 'marketing',
  },
  {
    keyword: 'local seo guide',
    searchVolume: 4000,
    difficulty: 15,
    intent: 'informational',
    relatedKeywords: ['local seo', 'google maps seo', 'local search optimization', 'google business profile'],
    contentType: 'blog',
    targetUrl: '/blog/local-seo-dominate-google-maps',
    category: 'seo',
  },
  {
    keyword: 'technical seo guide',
    searchVolume: 3000,
    difficulty: 12,
    intent: 'informational',
    relatedKeywords: ['technical seo', 'site speed seo', 'crawlability', 'indexing'],
    contentType: 'blog',
    targetUrl: '/blog/technical-seo-beginners-guide',
    category: 'seo',
  },
  {
    keyword: 'social media marketing guide',
    searchVolume: 5000,
    difficulty: 18,
    intent: 'informational',
    relatedKeywords: ['social media strategy', 'social media tips', 'social media marketing'],
    contentType: 'blog',
    targetUrl: '/blog/social-media-marketing-guide',
    category: 'marketing',
  },
  {
    keyword: 'instagram marketing grow followers',
    searchVolume: 4000,
    difficulty: 15,
    intent: 'informational',
    relatedKeywords: ['instagram growth', 'get instagram followers', 'instagram tips', 'grow instagram'],
    contentType: 'blog',
    targetUrl: '/blog/instagram-marketing-grow-10k',
    category: 'marketing',
  },
  {
    keyword: 'email marketing list building',
    searchVolume: 3500,
    difficulty: 12,
    intent: 'informational',
    relatedKeywords: ['build email list', 'email subscribers', 'email marketing tips'],
    contentType: 'blog',
    targetUrl: '/blog/email-marketing-build-list',
    category: 'marketing',
  },
  {
    keyword: 'content repurposing strategies',
    searchVolume: 2500,
    difficulty: 8,
    intent: 'informational',
    relatedKeywords: ['repurpose content', 'content recycling', 'multichannel content'],
    contentType: 'blog',
    targetUrl: '/blog/content-repurposing',
    category: 'content',
  },
  {
    keyword: 'image compression for web',
    searchVolume: 4000,
    difficulty: 12,
    intent: 'informational',
    relatedKeywords: ['web image optimization', 'image size for web', 'fast loading images'],
    contentType: 'blog',
    targetUrl: '/blog/compress-images-without-losing-quality',
    category: 'image',
  },
  {
    keyword: 'best image format for web',
    searchVolume: 3000,
    difficulty: 10,
    intent: 'informational',
    relatedKeywords: ['webp vs jpeg', 'png vs jpg', 'image format comparison'],
    contentType: 'blog',
    targetUrl: '/blog/best-image-formats-web',
    category: 'image',
  },
  {
    keyword: 'image seo optimization',
    searchVolume: 3500,
    difficulty: 12,
    intent: 'informational',
    relatedKeywords: ['optimize images for google', 'image alt text', 'image seo tips'],
    contentType: 'blog',
    targetUrl: '/blog/image-seo-optimize-images-google',
    category: 'image',
  },
  {
    keyword: 'how to remove image background',
    searchVolume: 6000,
    difficulty: 15,
    intent: 'informational',
    relatedKeywords: ['remove background free', 'transparent background', 'bg remover tool'],
    contentType: 'blog',
    targetUrl: '/blog/remove-image-backgrounds-free',
    category: 'image',
  },
  {
    keyword: 'batch image processing',
    searchVolume: 2500,
    difficulty: 8,
    intent: 'informational',
    relatedKeywords: ['batch resize images', 'bulk image editor', 'process multiple images'],
    contentType: 'blog',
    targetUrl: '/blog/batch-image-processing',
    category: 'image',
  },
  {
    keyword: 'best free pdf tools',
    searchVolume: 5000,
    difficulty: 15,
    intent: 'informational',
    relatedKeywords: ['pdf tools free', 'online pdf tools', 'pdf software free'],
    contentType: 'blog',
    targetUrl: '/blog/best-free-pdf-tools-students',
    category: 'pdf',
  },
  {
    keyword: 'how to edit pdf files',
    searchVolume: 8000,
    difficulty: 20,
    intent: 'informational',
    relatedKeywords: ['edit pdf', 'pdf editor free', 'modify pdf', 'pdf editing tool'],
    contentType: 'blog',
    targetUrl: '/blog/edit-pdf-files-free',
    category: 'pdf',
  },
  {
    keyword: 'pdf security protect documents',
    searchVolume: 3000,
    difficulty: 10,
    intent: 'informational',
    relatedKeywords: ['protect pdf', 'pdf encryption', 'secure pdf', 'lock pdf file'],
    contentType: 'blog',
    targetUrl: '/blog/pdf-security-protect-documents',
    category: 'pdf',
  },
  {
    keyword: 'chatgpt vs gemini comparison',
    searchVolume: 8000,
    difficulty: 20,
    intent: 'informational',
    relatedKeywords: ['chatgpt or gemini', 'ai comparison', 'best ai assistant'],
    contentType: 'blog',
    targetUrl: '/blog/chatgpt-vs-gemini',
    category: 'ai',
  },
  {
    keyword: 'ai image generation guide',
    searchVolume: 5000,
    difficulty: 15,
    intent: 'informational',
    relatedKeywords: ['ai art guide', 'generate images ai', 'text to image guide'],
    contentType: 'blog',
    targetUrl: '/blog/ai-image-generation-guide',
    category: 'ai',
  },
  {
    keyword: 'future of ai in marketing',
    searchVolume: 3000,
    difficulty: 10,
    intent: 'informational',
    relatedKeywords: ['ai marketing trends', 'ai digital marketing', 'marketing automation'],
    contentType: 'blog',
    targetUrl: '/blog/future-ai-digital-marketing',
    category: 'ai',
  },
  {
    keyword: 'how to use ai for content',
    searchVolume: 4000,
    difficulty: 12,
    intent: 'informational',
    relatedKeywords: ['ai content creation', 'ai writing guide', 'ai for bloggers'],
    contentType: 'blog',
    targetUrl: '/blog/use-ai-write-better-content',
    category: 'ai',
  },
  {
    keyword: 'youtube monetization without subscribers',
    searchVolume: 5000,
    difficulty: 12,
    intent: 'informational',
    relatedKeywords: ['youtube income', 'earn youtube money', 'youtube affiliate'],
    contentType: 'blog',
    targetUrl: '/blog/make-money-youtube-without-1000-subscribers',
    category: 'youtube',
  },
  {
    keyword: 'youtube channel trailer tips',
    searchVolume: 2000,
    difficulty: 6,
    intent: 'informational',
    relatedKeywords: ['channel trailer', 'youtube intro', 'channel trailer template'],
    contentType: 'blog',
    targetUrl: '/blog/youtube-channel-trailer-that-converts',
    category: 'youtube',
  },
  {
    keyword: 'video editing tips watch time',
    searchVolume: 2500,
    difficulty: 8,
    intent: 'informational',
    relatedKeywords: ['video editing', 'watch time tips', 'youtube editing'],
    contentType: 'blog',
    targetUrl: '/blog/video-editing-tips-fast-results',
    category: 'youtube',
  },
  {
    keyword: 'compelling headline formulas',
    searchVolume: 3000,
    difficulty: 10,
    intent: 'informational',
    relatedKeywords: ['headline formulas', 'write headlines', 'headline tips', 'blog headlines'],
    contentType: 'blog',
    targetUrl: '/blog/write-compelling-headlines',
    category: 'content',
  },
  {
    keyword: 'create content calendar',
    searchVolume: 4000,
    difficulty: 12,
    intent: 'informational',
    relatedKeywords: ['content planning', 'editorial calendar', 'content schedule'],
    contentType: 'blog',
    targetUrl: '/blog/create-content-calendar',
    category: 'content',
  },
  {
    keyword: 'ai content creation best practices',
    searchVolume: 3000,
    difficulty: 10,
    intent: 'informational',
    relatedKeywords: ['ai content tips', 'ai writing best practices', 'ai content strategy'],
    contentType: 'blog',
    targetUrl: '/blog/ai-content-creation-tools',
    category: 'ai',
  },
  {
    keyword: 'viral social media content',
    searchVolume: 4000,
    difficulty: 12,
    intent: 'informational',
    relatedKeywords: ['viral content', 'social media viral', 'create viral posts'],
    contentType: 'blog',
    targetUrl: '/blog/create-viral-social-media-content',
    category: 'content',
  },
  {
    keyword: 'seo vs sem comparison',
    searchVolume: 3000,
    difficulty: 10,
    intent: 'informational',
    relatedKeywords: ['seo or sem', 'organic vs paid', 'search marketing comparison'],
    contentType: 'blog',
    targetUrl: '/blog/seo-vs-sem-which-is-better',
    category: 'seo',
  },
  {
    keyword: 'fix common seo mistakes',
    searchVolume: 3500,
    difficulty: 10,
    intent: 'informational',
    relatedKeywords: ['seo errors', 'seo problems', 'seo issues', 'seo fixes'],
    contentType: 'blog',
    targetUrl: '/blog/fix-common-seo-mistakes',
    category: 'seo',
  },
  {
    keyword: 'facebook ads guide beginners',
    searchVolume: 5000,
    difficulty: 18,
    intent: 'informational',
    relatedKeywords: ['facebook advertising', 'fb ads', 'facebook ad campaign'],
    contentType: 'blog',
    targetUrl: '/blog/run-facebook-ads-convert',
    category: 'marketing',
  },
  {
    keyword: 'image ai enhancer',
    searchVolume: 4000,
    difficulty: 12,
    intent: 'transactional',
    relatedKeywords: ['enhance image', 'ai image enhancement', 'improve image quality'],
    contentType: 'tool',
    targetUrl: '/tools/ai-image-upscaler',
    category: 'image',
  },
  {
    keyword: 'ai sentiment analysis',
    searchVolume: 3000,
    difficulty: 10,
    intent: 'transactional',
    relatedKeywords: ['sentiment analysis tool', 'emotion analysis', 'text sentiment'],
    contentType: 'tool',
    targetUrl: '/tools/ai-sentiment-analyzer',
    category: 'ai',
  },
  {
    keyword: 'create qr code for wifi',
    searchVolume: 5000,
    difficulty: 12,
    intent: 'transactional',
    relatedKeywords: ['wifi qr code', 'qr code wifi', 'share wifi qr'],
    contentType: 'tool',
    targetUrl: '/tools/qr-code-generator',
    category: 'utility',
  },
  {
    keyword: 'js minifier online',
    searchVolume: 3000,
    difficulty: 10,
    intent: 'transactional',
    relatedKeywords: ['minify javascript', 'js compressor', 'javascript minify'],
    contentType: 'tool',
    targetUrl: '/tools/js-minifier',
    category: 'developer',
  },
  {
    keyword: 'image filter effects online',
    searchVolume: 4000,
    difficulty: 12,
    intent: 'transactional',
    relatedKeywords: ['photo filter online', 'image effects', 'apply filter'],
    contentType: 'tool',
    targetUrl: '/tools/image-filters',
    category: 'image',
  },
  {
    keyword: 'ai document summarizer free',
    searchVolume: 4000,
    difficulty: 12,
    intent: 'transactional',
    relatedKeywords: ['summarize pdf free', 'ai text summary', 'document summary tool'],
    contentType: 'tool',
    targetUrl: '/tools/ai-document-summarizer',
    category: 'ai',
  },
  {
    keyword: 'youtube video script template',
    searchVolume: 3000,
    difficulty: 10,
    intent: 'informational',
    relatedKeywords: ['video script', 'youtube script', 'script template'],
    contentType: 'blog',
    targetUrl: '/blog/write-viral-youtube-titles',
    category: 'youtube',
  },
];

// ===== CATEGORY KEYWORD CLUSTERS =====
export const KEYWORD_CLUSTERS: Record<string, string[]> = {
  'image-tools': [
    'image compressor', 'background remover', 'image resizer', 'image cropper',
    'image converter', 'image upscaler', 'image filters', 'favicon generator',
    'image to base64', 'color picker from image', 'image splitter', 'image merger',
    'image metadata', 'batch image processing', 'image optimization',
  ],
  'pdf-tools': [
    'pdf merger', 'pdf splitter', 'pdf compressor', 'pdf to jpg', 'jpg to pdf',
    'pdf rotator', 'pdf remover', 'pdf page numberer', 'pdf watermark',
    'pdf password protector', 'pdf unlocker', 'pdf metadata editor',
    'merge pdf', 'compress pdf', 'pdf converter',
  ],
  'youtube-tools': [
    'youtube title generator', 'youtube description generator', 'youtube tag generator',
    'youtube hashtag generator', 'youtube thumbnail downloader', 'youtube script writer',
    'youtube seo checker', 'youtube channel analyzer', 'youtube comment replies',
    'youtube video ideas', 'youtube algorithm', 'youtube growth',
  ],
  'developer-tools': [
    'json formatter', 'base64 encoder', 'url encoder', 'hash generator',
    'regex tester', 'css minifier', 'js minifier', 'html to markdown',
    'markdown to html', 'color code converter', 'password generator',
  ],
  'finance-tools': [
    'emi calculator', 'sip calculator', 'age calculator', 'bmi calculator',
    'percentage calculator', 'date difference', 'unit converter',
    'loan comparison', 'password generator',
  ],
  'ai-tools': [
    'ai background remover', 'ai image upscaler', 'ai text to image',
    'ai document summarizer', 'ai chatbot', 'ai code generator',
    'ai translator', 'ai sentiment analyzer', 'ai tools for creators',
  ],
  'seo-content': [
    'seo checklist', 'keyword research', 'on-page seo', 'technical seo',
    'backlinks', 'local seo', 'meta description', 'content marketing',
    'blog writing', 'content strategy',
  ],
  'youtube-content': [
    'youtube growth', 'youtube monetization', 'youtube algorithm',
    'youtube thumbnails', 'youtube titles', 'youtube shorts',
    'youtube channel', 'youtube strategy',
  ],
};

// ===== SEARCH INTENT ANALYSIS =====
export const INTENT_DISTRIBUTION = {
  transactional: PRIMARY_KEYWORDS.filter(k => k.intent === 'transactional').length + LONG_TAIL_KEYWORDS.filter(k => k.intent === 'transactional').length,
  informational: PRIMARY_KEYWORDS.filter(k => k.intent === 'informational').length + LONG_TAIL_KEYWORDS.filter(k => k.intent === 'informational').length,
  navigational: PRIMARY_KEYWORDS.filter(k => k.intent === 'navigational').length + LONG_TAIL_KEYWORDS.filter(k => k.intent === 'navigational').length,
};

// ===== UTILITY FUNCTIONS =====
export function getKeywordsByCategory(category: string): Keyword[] {
  return [...PRIMARY_KEYWORDS, ...LONG_TAIL_KEYWORDS].filter(k => k.category === category);
}

export function getKeywordsByIntent(intent: string): Keyword[] {
  return [...PRIMARY_KEYWORDS, ...LONG_TAIL_KEYWORDS].filter(k => k.intent === intent);
}

export function getLowCompetitionKeywords(maxDifficulty: number = 20): Keyword[] {
  return LONG_TAIL_KEYWORDS.filter(k => k.difficulty <= maxDifficulty);
}

export function getHighVolumeKeywords(minVolume: number = 10000): Keyword[] {
  return [...PRIMARY_KEYWORDS, ...LONG_TAIL_KEYWORDS].filter(k => k.searchVolume >= minVolume);
}

export function searchKeywords(query: string): Keyword[] {
  const q = query.toLowerCase();
  return [...PRIMARY_KEYWORDS, ...LONG_TAIL_KEYWORDS].filter(k =>
    k.keyword.includes(q) || k.relatedKeywords.some(rk => rk.includes(q))
  );
}

export function getTotalEstimatedTraffic(): number {
  return [...PRIMARY_KEYWORDS, ...LONG_TAIL_KEYWORDS].reduce((sum, k) => sum + k.searchVolume, 0);
}
