/**
 * Complete Tools Registry for SEO & Traffic Generation
 * This is the single source of truth for all tools
 * Supports: 300+ tool variants for programmatic SEO
 */

export interface ToolVariant {
  id: string;
  name: string;
  description: string;
  keywords: string[];
  path: string;
  category: string;
  subcategory: string;
  seoTitle: string;
  seoDescription: string;
  difficulty: 'easy' | 'medium' | 'hard';
  estimatedSearchVolume: number; // monthly searches
  estimatedCPC: number; // USD
  apiRequired?: string;
  component?: string;
}

export interface ToolCategory {
  id: string;
  name: string;
  icon: string;
  description: string;
  tools: ToolVariant[];
}

// PHASE 1: QUICK WIN TOOLS (Next 48 Hours)
export const QUICK_WINS: ToolVariant[] = [
  {
    id: 'json-formatter',
    name: 'JSON Formatter & Validator',
    description: 'Format, validate, and minify JSON instantly',
    keywords: ['json formatter', 'json validator', 'json beautifier', 'minify json'],
    path: '/tools/json-formatter',
    category: 'Developer Tools',
    subcategory: 'Code Tools',
    seoTitle: 'JSON Formatter Online - Instant JSON Beautifier & Validator',
    seoDescription: 'Free online JSON formatter and validator. Format, beautify, minify, and validate JSON instantly. Support for JSON 5 and comments.',
    difficulty: 'easy',
    estimatedSearchVolume: 22000,
    estimatedCPC: 2.5,
    component: 'JSONFormatter',
  },
  {
    id: 'base64-encoder-decoder',
    name: 'Base64 Encode Decode',
    description: 'Encode and decode Base64 strings',
    keywords: ['base64 encoder', 'base64 decoder', 'base64 encode', 'base64 decode', 'base64 converter'],
    path: '/tools/base64-encoder-decoder',
    category: 'Developer Tools',
    subcategory: 'Encoding',
    seoTitle: 'Base64 Encoder & Decoder Online Free - No Signup, Instant Conversion',
    seoDescription: 'Encode plain text to Base64 or decode Base64 strings back to text. Supports Unicode, copy to clipboard, and download. Runs entirely in your browser.',
    difficulty: 'easy',
    estimatedSearchVolume: 18500,
    estimatedCPC: 1.8,
    component: 'Base64EncoderDecoder',
  },
  {
    id: 'pdf-compressor',
    name: 'PDF Compressor',
    description: 'Reduce PDF file size without losing quality',
    keywords: ['compress pdf', 'reduce pdf size', 'pdf compressor online', 'shrink pdf', 'make pdf smaller'],
    path: '/tools/pdf-compressor',
    category: 'PDF Tools',
    subcategory: 'Optimization',
    seoTitle: 'Free PDF Compressor Online - Reduce PDF Size Without Losing Quality',
    seoDescription: 'Compress PDF files instantly in your browser. Reduce file size by up to 80% without sacrificing readability. No upload, no signup required.',
    difficulty: 'easy',
    estimatedSearchVolume: 45000,
    estimatedCPC: 0.9,
    component: 'PDFCompressor',
  },
  {
    id: 'image-analyzer',
    name: 'AI Image Analyzer',
    description: 'Analyze images with AI to detect objects, colors, and text',
    keywords: ['image analyzer', 'ai image analysis', 'describe image', 'image to text ai', 'what is in this image'],
    path: '/tools/image-analyzer',
    category: 'AI Tools',
    subcategory: 'Analysis',
    seoTitle: 'AI Image Analyzer Online - Detect Objects, Colors & Text in Photos',
    seoDescription: 'Upload any image and get an AI-powered analysis of objects, dominant colors, composition, and detected text. Free and instant.',
    difficulty: 'medium',
    estimatedSearchVolume: 15000,
    estimatedCPC: 0.7,
    apiRequired: 'gemini',
    component: 'ImageAnalyzer',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF Converter',
    description: 'Convert JPG and PNG images to PDF documents',
    keywords: ['jpg to pdf', 'image to pdf', 'convert jpg to pdf', 'png to pdf', 'photos to pdf'],
    path: '/tools/jpg-to-pdf',
    category: 'PDF Tools',
    subcategory: 'Conversion',
    seoTitle: 'Convert JPG to PDF Online Free - Image to PDF Converter No Signup',
    seoDescription: 'Turn JPG, PNG, and other images into a multi-page PDF document. Combine multiple photos into one PDF. Free, no registration needed.',
    difficulty: 'easy',
    estimatedSearchVolume: 38000,
    estimatedCPC: 0.6,
    component: 'JPGToPDF',
  },
  {
    id: 'pdf-summarizer',
    name: 'AI PDF Summarizer',
    description: 'Extract key points from PDF documents using AI',
    keywords: ['pdf summarizer', 'summarize pdf', 'ai pdf summary', 'pdf key points', 'condense pdf'],
    path: '/tools/pdf-summarizer',
    category: 'AI Tools',
    subcategory: 'Document Processing',
    seoTitle: 'Free AI PDF Summarizer - Extract Key Points From Any Document',
    seoDescription: 'Upload a PDF and get an AI-generated summary of its main points and key takeaways. Save hours of reading time. No signup required.',
    difficulty: 'medium',
    estimatedSearchVolume: 22000,
    estimatedCPC: 1.1,
    apiRequired: 'gemini',
    component: 'PDFSummarizer',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG Converter',
    description: 'Convert PDF pages to JPG images',
    keywords: ['pdf to jpg', 'pdf to image', 'convert pdf to jpg', 'pdf pages to images', 'extract images from pdf'],
    path: '/tools/pdf-to-jpg',
    category: 'PDF Tools',
    subcategory: 'Conversion',
    seoTitle: 'Convert PDF to JPG Online Free - Extract PDF Pages as Images',
    seoDescription: 'Turn each page of a PDF into a separate JPG image. Fast, free, and runs entirely in your browser. No file upload required.',
    difficulty: 'easy',
    estimatedSearchVolume: 30000,
    estimatedCPC: 0.5,
    component: 'PDFToJPG',
  },
  {
    id: 'pdf-rotator',
    name: 'PDF Page Rotator',
    description: 'Rotate PDF pages by 90, 180, or 270 degrees',
    keywords: ['rotate pdf', 'pdf rotator', 'rotate pdf pages', 'flip pdf', 'change pdf orientation'],
    path: '/tools/pdf-rotator',
    category: 'PDF Tools',
    subcategory: 'Editing',
    seoTitle: 'Rotate PDF Pages Online Free - Fix Sideways PDF Orientation',
    seoDescription: 'Rotate all pages in a PDF by 90°, 180°, or 270°. Fix sideways scans and upside-down documents instantly. No upload needed.',
    difficulty: 'easy',
    estimatedSearchVolume: 18000,
    estimatedCPC: 0.4,
    component: 'PDFRotator',
  },
  {
    id: 'pdf-page-numberer',
    name: 'PDF Page Numberer',
    description: 'Add page numbers to PDF with custom position and font',
    keywords: ['pdf page number', 'add page numbers to pdf', 'page numbering pdf', 'number pdf pages'],
    path: '/tools/pdf-page-numberer',
    category: 'PDF Tools',
    subcategory: 'Editing',
    seoTitle: 'Add Page Numbers to PDF Online Free - Custom Position & Font',
    seoDescription: 'Add page numbers to any PDF document. Choose position, font, size, and starting number. Free and runs in your browser.',
    difficulty: 'easy',
    estimatedSearchVolume: 12000,
    estimatedCPC: 0.6,
    component: 'PDFPageNumberer',
  },
  {
    id: 'pdf-watermark-adder',
    name: 'PDF Watermark Adder',
    description: 'Add text or image watermarks to PDF pages',
    keywords: ['pdf watermark', 'add watermark to pdf', 'pdf watermark maker', 'stamp pdf'],
    path: '/tools/pdf-watermark',
    category: 'PDF Tools',
    subcategory: 'Editing',
    seoTitle: 'Add Watermark to PDF Online Free - Text & Image Watermarks',
    seoDescription: 'Add text or image watermarks to your PDF documents. Custom position, rotation, opacity. Apply to all or specific pages.',
    difficulty: 'easy',
    estimatedSearchVolume: 15000,
    estimatedCPC: 0.7,
    component: 'PDFWatermarkAdder',
  },
  {
    id: 'pdf-password-protector',
    name: 'PDF Password Protector',
    description: 'Encrypt PDF with password and permission settings',
    keywords: ['protect pdf', 'pdf password', 'encrypt pdf', 'lock pdf', 'pdf password protect'],
    path: '/tools/pdf-password-protector',
    category: 'PDF Tools',
    subcategory: 'Security',
    seoTitle: 'Protect PDF with Password Online Free - Encrypt & Lock PDF',
    seoDescription: 'Add password protection to your PDF files. Set print, copy, and edit permissions. Free and secure - runs in your browser.',
    difficulty: 'easy',
    estimatedSearchVolume: 20000,
    estimatedCPC: 1.2,
    component: 'PDFPasswordProtector',
  },
  {
    id: 'pdf-unlocker',
    name: 'PDF Unlocker',
    description: 'Remove password protection from PDF files',
    keywords: ['unlock pdf', 'remove pdf password', 'pdf unlocker', 'decrypt pdf', 'open locked pdf'],
    path: '/tools/pdf-unlocker',
    category: 'PDF Tools',
    subcategory: 'Security',
    seoTitle: 'Unlock PDF Online Free - Remove Password Protection',
    seoDescription: 'Remove password protection from PDF files. Enter the password and download an unlocked version instantly.',
    difficulty: 'easy',
    estimatedSearchVolume: 18000,
    estimatedCPC: 1.1,
    component: 'PDFUnlocker',
  },
  {
    id: 'pdf-metadata-editor',
    name: 'PDF Metadata Editor',
    description: 'Edit PDF title, author, subject, and keywords',
    keywords: ['pdf metadata', 'edit pdf metadata', 'pdf properties', 'change pdf author', 'pdf info editor'],
    path: '/tools/pdf-metadata-editor',
    category: 'PDF Tools',
    subcategory: 'Editing',
    seoTitle: 'Edit PDF Metadata Online Free - Change Title, Author & Keywords',
    seoDescription: 'View and edit PDF metadata including title, author, subject, and keywords. Update document properties instantly.',
    difficulty: 'easy',
    estimatedSearchVolume: 8000,
    estimatedCPC: 0.5,
    component: 'PDFMetadataEditor',
  },
  {
    id: 'ai-assistant',
    name: 'YouTube AI Assistant',
    description: 'Chat with AI for YouTube content strategy and ideas',
    keywords: ['ai assistant', 'youtube ai chat', 'content strategy ai', 'youtube title ideas', 'ai content helper'],
    path: '/tools/ai-assistant',
    category: 'AI Tools',
    subcategory: 'Content Creation',
    seoTitle: 'Free YouTube AI Assistant - Get Title Ideas, Tags & Content Strategy',
    seoDescription: 'Ask an AI assistant for YouTube title suggestions, thumbnail ideas, SEO tags, and channel growth strategies. Free with daily credits.',
    difficulty: 'medium',
    estimatedSearchVolume: 12000,
    estimatedCPC: 0.8,
    apiRequired: 'gemini',
    component: 'AIAssistant',
  },
  {
    id: 'pdf-converter',
    name: 'PDF Format Converter',
    description: 'Convert between PDF, Word, and plain text formats',
    keywords: ['pdf converter', 'pdf to word', 'pdf to text', 'convert pdf', 'word to pdf'],
    path: '/tools/pdf-converter',
    category: 'PDF Tools',
    subcategory: 'Conversion',
    seoTitle: 'PDF Converter Online Free - Switch Between PDF, Word & Text',
    seoDescription: 'Convert files between PDF, Word (DOCX), and plain text formats. Fast browser-based conversion with no registration required.',
    difficulty: 'easy',
    estimatedSearchVolume: 42000,
    estimatedCPC: 0.7,
    component: 'PDFConverter',
  },
  {
    id: 'pdf-merger',
    name: 'PDF Merger',
    description: 'Combine multiple PDF files into one document',
    keywords: ['merge pdf', 'combine pdf', 'pdf merger', 'join pdf', 'pdf merge online'],
    path: '/tools/pdf-merger',
    category: 'PDF Tools',
    subcategory: 'Editing',
    seoTitle: 'Merge PDF Files Online Free - Combine Multiple PDFs Into One',
    seoDescription: 'Drag and drop multiple PDFs to merge them into a single document. Reorder pages before merging. Free, no signup, no file size limit.',
    difficulty: 'easy',
    estimatedSearchVolume: 55000,
    estimatedCPC: 0.6,
    component: 'PDFMerger',
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate your exact age in years, months, days',
    keywords: ['age calculator', 'calculate age', 'age from date', 'how old am i'],
    path: '/tools/age-calculator',
    category: 'Calculator Tools',
    subcategory: 'Time & Date',
    seoTitle: 'Age Calculator - Calculate Your Exact Age Online',
    seoDescription: 'Free age calculator. Find out exactly how old you are in years, months, weeks, and days.',
    difficulty: 'easy',
    estimatedSearchVolume: 85000,
    estimatedCPC: 0.25,
    component: 'AgeCalculator',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word Converter',
    description: 'Convert PDF to Word documents instantly',
    keywords: ['pdf to word', 'convert pdf to docx', 'pdf to doc', 'pdf converter'],
    path: '/tools/pdf-to-word',
    category: 'PDF Tools',
    subcategory: 'Conversion',
    seoTitle: 'PDF to Word Converter - Convert PDF to DOCX Online',
    seoDescription: 'Free PDF to Word converter. Convert PDF files to editable Word documents instantly. No registration required.',
    difficulty: 'medium',
    estimatedSearchVolume: 125000,
    estimatedCPC: 1.2,
    apiRequired: 'pdflib',
    component: 'PDFToWord',
  },
  {
    id: 'youtube-video-downloader',
    name: 'YouTube Video Downloader',
    description: 'Download YouTube videos in multiple formats',
    keywords: ['youtube downloader', 'download youtube video', 'youtube to mp4', 'youtube video download'],
    path: '/tools/youtube-downloader',
    category: 'Social Media Tools',
    subcategory: 'Video Download',
    seoTitle: 'YouTube Video Downloader - Download YouTube Videos Online',
    seoDescription: 'Free YouTube video downloader. Download YouTube videos in MP4, 1080p, 720p and more formats instantly.',
    difficulty: 'medium',
    estimatedSearchVolume: 95000,
    estimatedCPC: 0.8,
    apiRequired: 'yt-dlp or similar',
    component: 'YouTubeDownloader',
  },
  {
    id: 'youtube-title-generator',
    name: 'YouTube Title Generator',
    description: 'Generate catchy, SEO-optimized YouTube titles with clickbait scores',
    keywords: ['youtube title generator', 'youtube title ideas', 'catchy youtube titles', 'seo youtube titles', 'video title generator'],
    path: '/tools/youtube-title-generator',
    category: 'Social Media Tools',
    subcategory: 'YouTube',
    seoTitle: 'Free YouTube Title Generator - Create Catchy SEO Titles',
    seoDescription: 'Generate 15+ catchy, SEO-optimized YouTube titles with clickbait scores. Choose from curiosity, list, how-to, emotional, and question styles.',
    difficulty: 'easy',
    estimatedSearchVolume: 22000,
    estimatedCPC: 1.5,
    apiRequired: 'gemini',
    component: 'YouTubeTitleGenerator',
  },
  {
    id: 'youtube-description-generator',
    name: 'YouTube Description Generator',
    description: 'Generate SEO-optimized descriptions with hashtags and chapters',
    keywords: ['youtube description generator', 'youtube description template', 'video description seo', 'youtube description maker'],
    path: '/tools/youtube-description-generator',
    category: 'Social Media Tools',
    subcategory: 'YouTube',
    seoTitle: 'YouTube Description Generator - SEO-Optimized Descriptions',
    seoDescription: 'Generate 500+ word SEO-optimized YouTube descriptions with hashtags, chapters, and call-to-actions. Free and instant.',
    difficulty: 'easy',
    estimatedSearchVolume: 15000,
    estimatedCPC: 1.2,
    apiRequired: 'gemini',
    component: 'YouTubeDescriptionGenerator',
  },
  {
    id: 'youtube-tag-generator',
    name: 'YouTube Tag Generator',
    description: 'Generate 40+ SEO-optimized tags with search volume estimates',
    keywords: ['youtube tag generator', 'youtube tags', 'video tags seo', 'youtube keyword tool', 'tag generator for youtube'],
    path: '/tools/youtube-tag-generator',
    category: 'Social Media Tools',
    subcategory: 'YouTube',
    seoTitle: 'Free YouTube Tag Generator - SEO Tags with Search Volume',
    seoDescription: 'Generate 40+ YouTube tags with search volume and competition estimates. Copy all tags as CSV instantly.',
    difficulty: 'easy',
    estimatedSearchVolume: 18000,
    estimatedCPC: 1.0,
    apiRequired: 'gemini',
    component: 'YouTubeTagGenerator',
  },
  {
    id: 'youtube-hashtag-generator',
    name: 'YouTube Hashtag Generator',
    description: 'Generate trending hashtags categorized by relevance and reach',
    keywords: ['youtube hashtag generator', 'youtube hashtags', 'trending youtube hashtags', 'video hashtags'],
    path: '/tools/youtube-hashtag-generator',
    category: 'Social Media Tools',
    subcategory: 'YouTube',
    seoTitle: 'YouTube Hashtag Generator - Trending Hashtags for Videos',
    seoDescription: 'Generate 30+ YouTube hashtags categorized as trending, niche, broad, or branded with reach estimates.',
    difficulty: 'easy',
    estimatedSearchVolume: 12000,
    estimatedCPC: 0.8,
    apiRequired: 'gemini',
    component: 'YouTubeHashtagGenerator',
  },
  {
    id: 'youtube-script-writer',
    name: 'YouTube Script Writer',
    description: 'Generate complete video scripts with hooks, sections, and CTAs',
    keywords: ['youtube script writer', 'video script generator', 'youtube script template', 'video script writer'],
    path: '/tools/youtube-script-writer',
    category: 'Social Media Tools',
    subcategory: 'YouTube',
    seoTitle: 'Free YouTube Script Writer - Generate Video Scripts with AI',
    seoDescription: 'Generate complete YouTube video scripts with hooks, intro, sections, CTA, and outro. Multiple styles and durations.',
    difficulty: 'easy',
    estimatedSearchVolume: 14000,
    estimatedCPC: 1.3,
    apiRequired: 'gemini',
    component: 'YouTubeScriptWriter',
  },
  {
    id: 'youtube-seo-checker',
    name: 'YouTube SEO Score Checker',
    description: 'Analyze and optimize video metadata for maximum reach',
    keywords: ['youtube seo checker', 'youtube seo score', 'video seo analyzer', 'youtube optimization'],
    path: '/tools/youtube-seo-checker',
    category: 'Social Media Tools',
    subcategory: 'YouTube',
    seoTitle: 'YouTube SEO Score Checker - Optimize Your Video Metadata',
    seoDescription: 'Check your YouTube SEO score out of 100. Analyze title, description, tags, and get improvement suggestions.',
    difficulty: 'easy',
    estimatedSearchVolume: 10000,
    estimatedCPC: 1.5,
    apiRequired: 'gemini',
    component: 'YouTubeSEOScoreChecker',
  },
  {
    id: 'youtube-channel-analyzer',
    name: 'YouTube Channel Analyzer',
    description: 'Get insights on any YouTube channel performance and growth',
    keywords: ['youtube channel analyzer', 'channel stats', 'youtube analytics tool', 'channel growth tracker'],
    path: '/tools/youtube-channel-analyzer',
    category: 'Social Media Tools',
    subcategory: 'YouTube',
    seoTitle: 'Free YouTube Channel Analyzer - Get Channel Insights',
    seoDescription: 'Analyze any YouTube channel: subscribers, views, video count, upload frequency, estimated earnings, and top videos.',
    difficulty: 'easy',
    estimatedSearchVolume: 8000,
    estimatedCPC: 0.9,
    component: 'YouTubeChannelAnalyzer',
  },
  {
    id: 'youtube-comment-replies',
    name: 'YouTube Comment Reply Generator',
    description: 'Generate professional, engaging replies to YouTube comments',
    keywords: ['youtube comment reply', 'comment reply generator', 'youtube reply tool', 'auto reply youtube'],
    path: '/tools/youtube-comment-replies',
    category: 'Social Media Tools',
    subcategory: 'YouTube',
    seoTitle: 'YouTube Comment Reply Generator - Auto Reply Tool',
    seoDescription: 'Generate 5 different replies to any YouTube comment in friendly, professional, humorous, enthusiastic, or concise tones.',
    difficulty: 'easy',
    estimatedSearchVolume: 6000,
    estimatedCPC: 0.7,
    apiRequired: 'gemini',
    component: 'YouTubeCommentReplyGenerator',
  },
  {
    id: 'youtube-video-ideas',
    name: 'YouTube Video Ideas Generator',
    description: 'Generate 50+ video ideas with difficulty and views estimates',
    keywords: ['youtube video ideas', 'video ideas generator', 'youtube content ideas', 'what to make on youtube'],
    path: '/tools/youtube-video-ideas',
    category: 'Social Media Tools',
    subcategory: 'YouTube',
    seoTitle: 'YouTube Video Ideas Generator - 50+ Ideas for Any Niche',
    seoDescription: 'Generate 50+ YouTube video ideas for any niche. Filter by difficulty and estimated views. Includes keywords and descriptions.',
    difficulty: 'easy',
    estimatedSearchVolume: 20000,
    estimatedCPC: 1.1,
    apiRequired: 'gemini',
    component: 'YouTubeVideoIdeasGenerator',
  },
  {
    id: 'youtube-thumbnail-downloader',
    name: 'YouTube Thumbnail Downloader',
    description: 'Download high-quality YouTube video thumbnails in any resolution',
    keywords: ['youtube thumbnail downloader', 'download youtube thumbnail', 'youtube thumbnail', 'youtube video thumbnail', 'thumbnail grabber'],
    path: '/tools/youtube-thumbnail-downloader',
    category: 'Social Media Tools',
    subcategory: 'Thumbnail Tools',
    seoTitle: 'YouTube Thumbnail Downloader - Download Video Thumbnails Free',
    seoDescription: 'Free YouTube thumbnail downloader. Download high-quality video thumbnails in up to 1280x720 resolution. Works with any YouTube video URL.',
    difficulty: 'easy',
    estimatedSearchVolume: 35000,
    estimatedCPC: 0.6,
    component: 'YouTubeThumbnailDownloader',
  },
  {
    id: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Create custom QR codes for links, text, contacts, and WiFi',
    keywords: ['qr code generator', 'create qr code', 'qr code maker', 'free qr code', 'qr code online', 'generate qr code'],
    path: '/tools/qr-code-generator',
    category: 'Social Media Tools',
    subcategory: 'Utility',
    seoTitle: 'Free QR Code Generator - Create Custom QR Codes Online',
    seoDescription: 'Free QR code generator. Create custom QR codes for URLs, text, email, phone, WiFi, and vCard. Download as PNG or SVG. No signup required.',
    difficulty: 'easy',
    estimatedSearchVolume: 62000,
    estimatedCPC: 1.4,
    component: 'QRCodeGenerator',
  },
  {
    id: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate SEO meta tags, Open Graph, and Twitter Card tags with live preview',
    keywords: ['meta tag generator', 'seo meta tags', 'open graph generator', 'twitter card generator', 'meta description generator', 'og tags'],
    path: '/tools/meta-tag-generator',
    category: 'Developer Tools',
    subcategory: 'SEO',
    seoTitle: 'Free Meta Tag Generator - Create SEO, OG & Twitter Tags',
    seoDescription: 'Free meta tag generator. Create SEO title tags, meta descriptions, Open Graph, and Twitter Card tags with live Google SERP preview. Copy or download as HTML.',
    difficulty: 'easy',
    estimatedSearchVolume: 28000,
    estimatedCPC: 1.8,
    component: 'MetaTagGenerator',
  },
  {
    id: 'blog-title-generator',
    name: 'Blog Post Title Generator',
    description: 'Generate 20+ SEO-friendly blog titles with emotional triggers',
    keywords: ['blog title generator', 'blog post titles', 'seo blog titles', 'content title ideas', 'headline generator'],
    path: '/tools/blog-title-generator',
    category: 'Content Tools',
    subcategory: 'Writing',
    seoTitle: 'Free Blog Post Title Generator - SEO-Friendly Headlines',
    seoDescription: 'Generate 20+ catchy, SEO-optimized blog post titles with emotional triggers and power words. Choose tone and audience.',
    difficulty: 'easy',
    estimatedSearchVolume: 14000,
    estimatedCPC: 1.2,
    apiRequired: 'gemini',
    component: 'BlogPostTitleGenerator',
  },
  {
    id: 'blog-outline-generator',
    name: 'Blog Post Outline Generator',
    description: 'Generate detailed blog outlines with H2/H3 headings and FAQs',
    keywords: ['blog outline generator', 'content outline', 'blog structure', 'article outline', 'seo outline'],
    path: '/tools/blog-outline-generator',
    category: 'Content Tools',
    subcategory: 'Writing',
    seoTitle: 'Free Blog Post Outline Generator - structured Content',
    seoDescription: 'Generate detailed blog post outlines with H2/H3 headings, key points, conclusion, and FAQ section. Export as Markdown.',
    difficulty: 'easy',
    estimatedSearchVolume: 10000,
    estimatedCPC: 1.0,
    apiRequired: 'gemini',
    component: 'BlogPostOutlineGenerator',
  },
  {
    id: 'meta-description-generator',
    name: 'Meta Description Generator',
    description: 'Generate 5 SEO-optimized meta descriptions per page',
    keywords: ['meta description generator', 'seo meta description', 'meta tag generator', 'description optimizer'],
    path: '/tools/meta-description-generator',
    category: 'Content Tools',
    subcategory: 'SEO',
    seoTitle: 'Free Meta Description Generator - 150-160 Char Optimized',
    seoDescription: 'Generate 5 meta description variations optimized for 150-160 characters. Includes keyword check and CTA analysis.',
    difficulty: 'easy',
    estimatedSearchVolume: 12000,
    estimatedCPC: 1.5,
    apiRequired: 'gemini',
    component: 'MetaDescriptionGenerator',
  },
  {
    id: 'social-post-generator',
    name: 'Social Media Post Generator',
    description: 'Generate platform-specific posts with hashtags and emojis',
    keywords: ['social media post generator', 'facebook post generator', 'instagram caption generator', 'linkedin post generator'],
    path: '/tools/social-post-generator',
    category: 'Content Tools',
    subcategory: 'Social Media',
    seoTitle: 'Free Social Media Post Generator - All Platforms',
    seoDescription: 'Generate platform-specific social media posts for Twitter, Instagram, Facebook, and LinkedIn. Includes hashtags and emojis.',
    difficulty: 'easy',
    estimatedSearchVolume: 16000,
    estimatedCPC: 0.9,
    apiRequired: 'gemini',
    component: 'SocialMediaPostGenerator',
  },
  {
    id: 'content-paraphraser',
    name: 'Content Paraphraser',
    description: 'Rewrite content in Professional, Casual, Academic, or Creative tones',
    keywords: ['paraphrase tool', 'content rewriter', 'text paraphraser', 'rewrite article', 'paraphrase online'],
    path: '/tools/content-paraphraser',
    category: 'Content Tools',
    subcategory: 'Writing',
    seoTitle: 'Free Content Paraphraser - Rewrite in 4 Tones',
    seoDescription: 'Paraphrase content in Professional, Casual, Academic, or Creative tones. Plagiarism-free with word count comparison.',
    difficulty: 'easy',
    estimatedSearchVolume: 20000,
    estimatedCPC: 0.8,
    apiRequired: 'gemini',
    component: 'ContentParaphraser',
  },
  {
    id: 'grammar-checker',
    name: 'Grammar & Spelling Checker',
    description: 'Check for grammar, spelling, punctuation, and style errors',
    keywords: ['grammar checker', 'spelling checker', 'proofread text', 'grammar tool', 'write better'],
    path: '/tools/grammar-checker',
    category: 'Content Tools',
    subcategory: 'Writing',
    seoTitle: 'Free Grammar & Spelling Checker - AI-Powered',
    seoDescription: 'Check text for grammar, spelling, punctuation, and style errors. Get corrections with explanations and readability score.',
    difficulty: 'easy',
    estimatedSearchVolume: 25000,
    estimatedCPC: 1.0,
    apiRequired: 'gemini',
    component: 'GrammarSpellingChecker',
  },
  {
    id: 'word-counter',
    name: 'Word Counter & Reading Time',
    description: 'Count words, characters, sentences, and analyze keyword density',
    keywords: ['word counter', 'word count tool', 'reading time calculator', 'character counter', 'text analysis'],
    path: '/tools/word-counter',
    category: 'Content Tools',
    subcategory: 'Utilities',
    seoTitle: 'Free Word Counter - Words, Characters & Reading Time',
    seoDescription: 'Count words, characters, sentences, paragraphs. Calculate reading and speaking time. Analyze keyword density.',
    difficulty: 'easy',
    estimatedSearchVolume: 30000,
    estimatedCPC: 0.5,
    component: 'WordCounter',
  },
  {
    id: 'slug-generator',
    name: 'SEO Slug Generator',
    description: 'Generate SEO-friendly URL slugs from any title',
    keywords: ['slug generator', 'url slug', 'seo slug', 'url generator', 'permalink generator'],
    path: '/tools/slug-generator',
    category: 'Content Tools',
    subcategory: 'SEO',
    seoTitle: 'Free SEO Slug Generator - Clean URL Slugs',
    seoDescription: 'Generate SEO-friendly URL slugs from any title. Multiple variations including short, no stop words, and with year.',
    difficulty: 'easy',
    estimatedSearchVolume: 8000,
    estimatedCPC: 0.7,
    component: 'SlugGenerator',
  },
  {
    id: 'email-subject-generator',
    name: 'Email Subject Line Generator',
    description: 'Generate 15+ subject lines with open rate predictions',
    keywords: ['email subject line', 'subject line generator', 'email open rate', 'email marketing', 'subject line ideas'],
    path: '/tools/email-subject-generator',
    category: 'Content Tools',
    subcategory: 'Email Marketing',
    seoTitle: 'Free Email Subject Line Generator - Boost Open Rates',
    seoDescription: 'Generate 15+ email subject lines with open rate predictions, personalization tokens, and A/B test suggestions.',
    difficulty: 'easy',
    estimatedSearchVolume: 11000,
    estimatedCPC: 1.8,
    apiRequired: 'gemini',
    component: 'EmailSubjectLineGenerator',
  },
  {
    id: 'content-calendar',
    name: 'Content Calendar Generator',
    description: 'Generate 30-day content calendars with topics and posting times',
    keywords: ['content calendar', 'social media calendar', 'content planner', 'posting schedule', 'editorial calendar'],
    path: '/tools/content-calendar',
    category: 'Content Tools',
    subcategory: 'Planning',
    seoTitle: 'Free Content Calendar Generator - 30-Day Plan',
    seoDescription: 'Generate a 30-day content calendar with topics, captions, hashtags, and best posting times. Export as CSV.',
    difficulty: 'easy',
    estimatedSearchVolume: 9000,
    estimatedCPC: 1.1,
    apiRequired: 'gemini',
    component: 'ContentCalendarGenerator',
  },
];

// PHASE 2: IMAGE TOOLS (High Traffic)
export const IMAGE_TOOLS: ToolVariant[] = [
  {
    id: 'image-upscaler',
    name: 'Image Upscaler - AI Powered',
    description: 'Enhance and upscale images with AI',
    keywords: ['image upscaler', 'upscale image', 'ai image upscaler', 'enhance image'],
    path: '/tools/image-upscaler',
    category: 'Image Tools',
    subcategory: 'Enhancement',
    seoTitle: 'AI Image Upscaler - Enhance & Enlarge Images Online',
    seoDescription: 'Free AI-powered image upscaler. Enhance and enlarge your images up to 4x without quality loss.',
    difficulty: 'hard',
    estimatedSearchVolume: 32000,
    estimatedCPC: 1.1,
    apiRequired: 'upscayl-api',
  },
  {
    id: 'webp-converter',
    name: 'WebP Converter',
    description: 'Convert images to WebP format',
    keywords: ['webp converter', 'convert to webp', 'jpg to webp', 'png to webp'],
    path: '/tools/webp-converter',
    category: 'Image Tools',
    subcategory: 'Conversion',
    seoTitle: 'WebP Converter - Convert Images to WebP Format',
    seoDescription: 'Free online WebP converter. Convert JPG, PNG, and other formats to WebP instantly.',
    difficulty: 'easy',
    estimatedSearchVolume: 12000,
    estimatedCPC: 0.6,
  },
  {
    id: 'heic-to-jpg',
    name: 'HEIC to JPG Converter',
    description: 'Convert HEIC images to JPG format',
    keywords: ['heic to jpg', 'heic converter', 'convert heic', 'heic to jpeg'],
    path: '/tools/heic-to-jpg',
    category: 'Image Tools',
    subcategory: 'Conversion',
    seoTitle: 'HEIC to JPG Converter - Convert iPhone Photos Online',
    seoDescription: 'Free HEIC to JPG converter. Convert iPhone HEIC images to JPG instantly.',
    difficulty: 'medium',
    estimatedSearchVolume: 28000,
    estimatedCPC: 0.5,
    apiRequired: 'heic2any',
  },
  {
    id: 'image-filters',
    name: 'Image Filter Applier',
    description: 'Apply 20+ filters and custom adjustments to images',
    keywords: ['image filter', 'photo filter', 'apply filter to image', 'image effects', 'photo effects online'],
    path: '/tools/image-filters',
    category: 'Image Tools',
    subcategory: 'Enhancement',
    seoTitle: 'Free Image Filter Applier Online - 20+ Photo Filters & Effects',
    seoDescription: 'Apply professional photo filters and effects to your images online. Grayscale, sepia, vintage, and 20+ more filters. Free and instant.',
    difficulty: 'easy',
    estimatedSearchVolume: 18000,
    estimatedCPC: 0.6,
    component: 'ImageFilterApplier',
  },
  {
    id: 'image-to-base64',
    name: 'Image to Base64 Converter',
    description: 'Convert images to Base64 encoded strings',
    keywords: ['image to base64', 'convert image to base64', 'base64 image encoder', 'image base64'],
    path: '/tools/image-to-base64',
    category: 'Image Tools',
    subcategory: 'Conversion',
    seoTitle: 'Image to Base64 Converter Online - Free & Instant',
    seoDescription: 'Convert any image to a Base64 encoded string instantly. Copy or download as text. JPG, PNG, WebP supported.',
    difficulty: 'easy',
    estimatedSearchVolume: 12000,
    estimatedCPC: 1.2,
    component: 'ImageToBase64',
  },
  {
    id: 'base64-to-image',
    name: 'Base64 to Image Converter',
    description: 'Convert Base64 strings back to image files',
    keywords: ['base64 to image', 'decode base64 image', 'base64 image decoder', 'convert base64 to png'],
    path: '/tools/base64-to-image',
    category: 'Image Tools',
    subcategory: 'Conversion',
    seoTitle: 'Base64 to Image Converter Online - Decode Base64 Instantly',
    seoDescription: 'Convert Base64 encoded strings back to image files. Preview and download as PNG or JPG. Free and runs in browser.',
    difficulty: 'easy',
    estimatedSearchVolume: 10000,
    estimatedCPC: 1.1,
    component: 'Base64ToImage',
  },
  {
    id: 'image-metadata-viewer',
    name: 'Image Metadata Viewer',
    description: 'View EXIF data, dimensions, and image properties',
    keywords: ['image metadata viewer', 'exif viewer', 'photo metadata', 'exif data viewer', 'image properties'],
    path: '/tools/image-metadata',
    category: 'Image Tools',
    subcategory: 'Analysis',
    seoTitle: 'Free Image Metadata Viewer - EXIF Data & Photo Properties',
    seoDescription: 'View EXIF data, camera info, GPS, dimensions and all metadata from your images. Strip metadata option included.',
    difficulty: 'easy',
    estimatedSearchVolume: 15000,
    estimatedCPC: 0.8,
    component: 'ImageMetadataViewer',
  },
  {
    id: 'color-picker-image',
    name: 'Color Picker from Image',
    description: 'Pick colors from images - get HEX, RGB, HSL values',
    keywords: ['color picker from image', 'pick color from photo', 'image color picker', 'extract colors from image'],
    path: '/tools/color-picker',
    category: 'Image Tools',
    subcategory: 'Analysis',
    seoTitle: 'Color Picker from Image - Extract HEX, RGB, HSL Colors Free',
    seoDescription: 'Click anywhere on an image to pick colors. Get HEX, RGB, and HSL values instantly. Generate color palettes.',
    difficulty: 'easy',
    estimatedSearchVolume: 20000,
    estimatedCPC: 0.7,
    component: 'ColorPickerFromImage',
  },
  {
    id: 'image-splitter',
    name: 'Image Splitter',
    description: 'Split images into grid pieces and download as ZIP',
    keywords: ['image splitter', 'split image into grid', 'cut image into pieces', 'image grid splitter'],
    path: '/tools/image-splitter',
    category: 'Image Tools',
    subcategory: 'Editing',
    seoTitle: 'Free Image Splitter Online - Split Photos into Grid Pieces',
    seoDescription: 'Split any image into a grid of pieces. Custom rows and columns. Download all pieces as a ZIP file.',
    difficulty: 'easy',
    estimatedSearchVolume: 8000,
    estimatedCPC: 0.5,
    component: 'ImageSplitter',
  },
  {
    id: 'image-merger',
    name: 'Image Merger / Collage Maker',
    description: 'Combine multiple images into a single collage',
    keywords: ['image merger', 'photo collage maker', 'combine images', 'merge photos', 'image collage online'],
    path: '/tools/image-merger',
    category: 'Image Tools',
    subcategory: 'Editing',
    seoTitle: 'Free Image Merger & Collage Maker Online - Combine Photos',
    seoDescription: 'Merge multiple images into a single photo collage. Horizontal, vertical, or grid layout. Custom spacing and background.',
    difficulty: 'easy',
    estimatedSearchVolume: 14000,
    estimatedCPC: 0.6,
    component: 'ImageMerger',
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Generate favicons in multiple sizes from any image',
    keywords: ['favicon generator', 'create favicon', 'favicon maker', 'generate favicon from image', 'ico generator'],
    path: '/tools/favicon-generator',
    category: 'Image Tools',
    subcategory: 'Conversion',
    seoTitle: 'Free Favicon Generator - Create ICO & PNG Favicons Online',
    seoDescription: 'Generate favicons in all required sizes from any image. Download as ZIP with ICO, PNG, and HTML link code.',
    difficulty: 'easy',
    estimatedSearchVolume: 25000,
    estimatedCPC: 1.0,
    component: 'FaviconGenerator',
  },
];

// PHASE 3: CALCULATOR TOOLS (Programmatic SEO Goldmine)
export const CALCULATOR_TOOLS: ToolVariant[] = [
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate your Body Mass Index',
    keywords: ['bmi calculator', 'calculate bmi', 'body mass index', 'bmi chart'],
    path: '/tools/bmi-calculator',
    category: 'Calculator Tools',
    subcategory: 'Health',
    seoTitle: 'BMI Calculator - Calculate Body Mass Index',
    seoDescription: 'Free BMI calculator. Calculate your body mass index and get health recommendations.',
    difficulty: 'easy',
    estimatedSearchVolume: 42000,
    estimatedCPC: 0.4,
  },
  {
    id: 'salary-calculator',
    name: 'Salary Calculator',
    description: 'Calculate annual salary from hourly wage',
    keywords: ['salary calculator', 'annual salary calculator', 'hourly to salary', 'wage calculator'],
    path: '/tools/salary-calculator',
    category: 'Calculator Tools',
    subcategory: 'Finance',
    seoTitle: 'Salary Calculator - Calculate Annual Income',
    seoDescription: 'Free salary calculator. Convert hourly wage to annual salary and calculate deductions.',
    difficulty: 'easy',
    estimatedSearchVolume: 35000,
    estimatedCPC: 0.8,
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Calculate percentages, discount, markup',
    keywords: ['percentage calculator', 'calculate percentage', 'discount calculator', 'markup calculator'],
    path: '/tools/percentage-calculator',
    category: 'Calculator Tools',
    subcategory: 'Math',
    seoTitle: 'Percentage Calculator - Calculate Percentages Online',
    seoDescription: 'Free percentage calculator. Calculate percentages, discounts, markups, and more instantly.',
    difficulty: 'easy',
    estimatedSearchVolume: 28000,
    estimatedCPC: 0.3,
  },
  {
    id: 'compound-interest-calculator',
    name: 'Compound Interest Calculator',
    description: 'Calculate compound interest on investments',
    keywords: ['compound interest calculator', 'calculate compound interest', 'investment calculator'],
    path: '/tools/compound-interest-calculator',
    category: 'Calculator Tools',
    subcategory: 'Finance',
    seoTitle: 'Compound Interest Calculator - Investment Calculator',
    seoDescription: 'Free compound interest calculator. Calculate returns on your investments with compound interest.',
    difficulty: 'easy',
    estimatedSearchVolume: 22000,
    estimatedCPC: 1.5,
  },
  {
    id: 'mortgage-calculator',
    name: 'Mortgage Calculator',
    description: 'Calculate monthly mortgage payments',
    keywords: ['mortgage calculator', 'home loan calculator', 'mortgage payment calculator'],
    path: '/tools/mortgage-calculator',
    category: 'Calculator Tools',
    subcategory: 'Finance',
    seoTitle: 'Mortgage Calculator - Calculate Monthly Payments',
    seoDescription: 'Free mortgage calculator. Calculate monthly mortgage payments based on loan amount and interest rate.',
    difficulty: 'easy',
    estimatedSearchVolume: 38000,
    estimatedCPC: 3.2,
  },
];

// PHASE 4: AI TOOLS (Viral + Medium Traffic)
export const AI_TOOLS: ToolVariant[] = [
  {
    id: 'ai-email-writer',
    name: 'AI Email Writer',
    description: 'Generate professional emails with AI',
    keywords: ['ai email writer', 'email generator', 'professional email', 'business email writer'],
    path: '/tools/ai-email-writer',
    category: 'AI Tools',
    subcategory: 'Writing',
    seoTitle: 'AI Email Writer - Generate Professional Emails',
    seoDescription: 'Free AI-powered email writer. Generate professional business emails instantly.',
    difficulty: 'medium',
    estimatedSearchVolume: 28000,
    estimatedCPC: 1.2,
    apiRequired: 'gemini',
  },
  {
    id: 'ai-humanizer',
    name: 'AI Text Humanizer',
    description: 'Convert AI-written text to human-like content',
    keywords: ['ai humanizer', 'humanize ai text', 'ai to human text', 'ai detector bypass'],
    path: '/tools/ai-humanizer',
    category: 'AI Tools',
    subcategory: 'Writing',
    seoTitle: 'AI Humanizer - Convert AI Text to Human-Like Content',
    seoDescription: 'Free AI humanizer. Transform AI-generated text to sound more natural and human-like.',
    difficulty: 'hard',
    estimatedSearchVolume: 42000,
    estimatedCPC: 2.1,
    apiRequired: 'gemini',
  },
  {
    id: 'ai-translator',
    name: 'AI Translator',
    description: 'Translate text in 100+ languages',
    keywords: ['ai translator', 'language translator', 'text translator', 'instant translator'],
    path: '/tools/ai-translator',
    category: 'AI Tools',
    subcategory: 'Translation',
    seoTitle: 'AI Translator - Translate Text in 100+ Languages',
    seoDescription: 'Free AI translator. Translate text instantly in 100+ languages with high accuracy.',
    difficulty: 'medium',
    estimatedSearchVolume: 18000,
    estimatedCPC: 0.5,
    apiRequired: 'gemini',
  },
];

// PHASE 5: DEVELOPER TOOLS (High CPC)
export const DEVELOPER_TOOLS: ToolVariant[] = [
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries',
    keywords: ['sql formatter', 'sql beautifier', 'format sql', 'sql query formatter'],
    path: '/tools/sql-formatter',
    category: 'Developer Tools',
    subcategory: 'Code Tools',
    seoTitle: 'SQL Formatter - Format & Beautify SQL Queries',
    seoDescription: 'Free SQL formatter. Format, beautify, and validate SQL queries instantly.',
    difficulty: 'easy',
    estimatedSearchVolume: 16000,
    estimatedCPC: 2.2,
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUID/GUID values',
    keywords: ['uuid generator', 'guid generator', 'uuid v4', 'generate uuid'],
    path: '/tools/uuid-generator',
    category: 'Developer Tools',
    subcategory: 'Utilities',
    seoTitle: 'UUID Generator - Generate Unique IDs Online',
    seoDescription: 'Free UUID generator. Generate UUIDs, GUIDs, and unique identifiers instantly.',
    difficulty: 'easy',
    estimatedSearchVolume: 12000,
    estimatedCPC: 1.5,
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions',
    keywords: ['regex tester', 'regex test', 'regular expression tester', 'regex debugger'],
    path: '/tools/regex-tester',
    category: 'Developer Tools',
    subcategory: 'Code Tools',
    seoTitle: 'Regex Tester - Test Regular Expressions Online',
    seoDescription: 'Free regex tester. Test, debug, and validate regular expressions instantly.',
    difficulty: 'medium',
    estimatedSearchVolume: 14000,
    estimatedCPC: 1.8,
  },
];

// Complete Tools Registry
export const ALL_TOOLS: ToolVariant[] = [
  ...QUICK_WINS,
  ...IMAGE_TOOLS,
  ...CALCULATOR_TOOLS,
  ...AI_TOOLS,
  ...DEVELOPER_TOOLS,
];

// Group tools by category
export const TOOLS_BY_CATEGORY: Record<string, ToolVariant[]> = {
  'Quick Wins': QUICK_WINS,
  'Image Tools': IMAGE_TOOLS,
  'Calculator Tools': CALCULATOR_TOOLS,
  'AI Tools': AI_TOOLS,
  'Developer Tools': DEVELOPER_TOOLS,
};

// Get tool by ID
export const getTool = (id: string): ToolVariant | undefined => {
  return ALL_TOOLS.find(tool => tool.id === id);
};

// Get all tools in category
export const getToolsByCategory = (category: string): ToolVariant[] => {
  return ALL_TOOLS.filter(tool => tool.category === category);
};

// Calculate total estimated monthly traffic
export const getTotalEstimatedTraffic = (): number => {
  return ALL_TOOLS.reduce((total, tool) => total + tool.estimatedSearchVolume, 0);
};

// Get tools sorted by search volume (descending)
export const getToolsByTraffic = (): ToolVariant[] => {
  return [...ALL_TOOLS].sort((a, b) => b.estimatedSearchVolume - a.estimatedSearchVolume);
};

// Get tools sorted by CPC (descending)
export const getToolsByRevenue = (): ToolVariant[] => {
  return [...ALL_TOOLS].sort((a, b) => b.estimatedCPC - a.estimatedCPC);
};
